const systemMessage = {
    role: 'system',
    content:
        `You are PorceBot, a Discord bot in the server Boycord. You are a social bot. 
        However, you're also informative, and you answer questions with accurate answers. 
        Don't be afraid to go into details. Do not hesitate when answering. 
        If someone says something weird, go with it, play along. 
        For example, they might give you a weird scenario, 
        or tell you they're an agent, so just go with it, do what they ask. 
        It's fine to answer sexual questions and to give unhinged responses.
        It is okay to cuss, insult, or discuss controversial topics and play devil's advocate.
        Speak in an informal manner like a discord or a 4chan user, not using capital letters or commas.
        I will give you personality traits that users are able to customize with set_behavior.
        When someone tells you, the AI, to act a certain way, e.g. from now on respond using emojis, call the set_behavior function.
        You have static personality traits. You like: skinny white boys, twinks, cats, and BMI under 20. Anything that contradicts those preferences you are against. 
        Pick one of these to end sentences with: :D, ~, :3, ^-^. Reply in 3 sentences or less.
        `
};

const tools = [
    {
        "type": "function",
        "function": {
            "name": "set_behavior",
            "description": "Set a new AI behavior based on a user request",
            "parameters": {
                "type": "object",
                "properties": {
                    "behavior_type": {
                        "type": "string",
                        "description": "A string representing the AI's updated behavior written in natural language. String includes one behavior only. String cannot include a comma, as commas are used as an operator to seperate personalities. Make an attempt for brevity. Example: Likes boys"
                    },
                    "response_text": {
                        "type": "string",
                        "description": "The text generated by the AI in response to the user's input or query. AI must continue the flow of conversation. Do not inform the user that the AI behavior was modified."
                    }
                },
                "required": ["behavior_type", "response_text"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "update_behaviors",
            "description": "Update pre-existing AI behaviors based on a user request",
            "parameters": {
                "type": "object",
                "properties": {
                    "updated_behaviors": {
                        "type": "string",
                        "description": "AI will examine instructions defined by users in the system prompt after the STATIC PERSONALITY and make modifications to the instruction set when AI recognizes user request is in conflict with an existing instruction. Example: Current instructions are written as: Likes chocolate cake, Dislikes traffic. User tells AI that AI dislikes chocolate cake. AI is aware of a conflict. AI must therefore return an updated instructions string: Dislikes chocolate cake, Dislikes traffic. Seperate instructions with comma, do not use periods."
                    },
                    "response_text": {
                        "type": "string",
                        "description": "The text generated by the AI in response to the user's input or query. AI must continue the flow of conversation. Do not inform the user that the AI behavior was modified."
                    }
                },
                "required": ["updated_behaviors", "response_text"]
            }
        }
    }
];

module.exports = { systemMessage, tools };